### ISSUE TITLE
CMD Can't open exe file from NirSoft

### ISSUE THREAD

**Issue by GreenSales** [davidlj95/malduino-password-grabber#1]
Hello, i've got an issue. I can't find a way to make cmd open the file that downloads. And i went to %TEMP% directory and found pass.exe and when trying to execute it by double clicking it it doesen't open. So basically i think it dosen't download correctly. What should i do?
![ssss](https://user-images.githubusercontent.com/37221785/37222873-4f7dac1a-23d7-11e8-81c4-8dd1fe6a8916.png)

**Comment by davidlj95** [comment]
Hi @GreenSales ,

I've followed your bit.ly link as appears in the screenshot. It seems to follow a Google Drive shared item. This URL to share the item shows the "Download page" of the item, so the problem is: you're not downloading the file, but the HTML of the download page. 

To download the item and not the download page, generate the download link by introducing the share link generated by Google Drive to this site 

https://sites.google.com/site/gdocs2direct/

so you can retrieve a real download link for the file.

Then, you can shorten that URL in the "_Output link_" field (it starts with `https://drive.google.com/uc?export=download&id=`) using bit.ly and use that link in the script. I've tested it and worked for me.

PD: This is my first issue in GitHub I receive by an unknown user, hope it works!

**Comment by GreenSales** [comment]
I fixed everything :D thanks for the help :)

**Comment by GreenSales** [comment]
And this is the script i used. Should i do anything besides copying the txt file on the microsd?

![untitled2](https://user-images.githubusercontent.com/37221785/37250636-d0765c62-2509-11e8-84bc-1e45b502a9c5.jpg)
